### PR TITLE
feat: update contentful dependencies in generated packagejson

### PR DESCRIPTION
**Pull request by Jwhiles**
Update our dependencies, we should consider ways to automate this process

### CODE REVIEW

**Comment by FLoppix** [comment]
So maybe we should add dependabot then

**Comment by Jwhiles** [comment]
> So maybe we should add dependabot then

@FLoppix  I don't know much about dependabot - but I wonder how well it would work in this case? As the deps are in a script file rather than a package.json.. I'll do some looking and see if it's possible :)

**Comment by FLoppix** [comment]
@Jwhiles ah sorry my bad. Thought it was in the `package.json` . Then I think it is a different story :D

**Comment by Jwhiles** [comment]
@suevalov I generated a typescript field extension and ran it successfully, do you want me to check the other extension types too? Out of interest, what makes you think that there might be issues?

**Comment by Jwhiles** [comment]
@FLoppix we could add the dependencies we care about to the package.json and then have a PR template for dependabot that tells people to update the template file? Not very elegant but maybe it's good enough.

**Comment by suevalov** [comment]
@Jwhiles would be nice to check all of them. In theory Forma36 follows semver but I would double check.

**Pull request merged**
